[global]
# Development mode - set to false for production
developmentMode = false

[server]
# Server settings
runOnSave = false
allowRunOnSave = false

# File watching
fileWatcherType = "auto"

# CORS and security
enableCORS = false
enableXsrfProtection = true

# Maximum upload size (200MB)
maxUploadSize = 200

# Maximum message size
maxMessageSize = 200

[browser]
# Gather usage stats for Streamlit Cloud
gatherUsageStats = true

[theme]
# Default theme - users can toggle between themes in the app
primaryColor = "#4361ee"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

# Font family
font = "sans serif"

[client]
# Show error details
showErrorDetails = true

# Toolbar mode
toolbarMode = "auto"

[runner]
# Magic commands
magicEnabled = true

# Fast rerun
fastReruns = true

# Post script gc
postScriptGC = true

[logger]
# Logging level
level = "info"

# Message format
messageFormat = "%(asctime)s %(message)s"